#+TITLE:Archemacs
#+AUTHOR:Archenoth
#+EMAIL:Archenoth@gmail.com
:SETTINGS:
#+STARTUP: hidestars inlineimages
#+TOC: headlines 1
:END:

This is my personal configuration for Emacs! It's largely Doom-Emacs themed, and specifically tweaked to be good at the things I personally like doing.

You can use it too if you like! But I can't really attest to the general-purpose nature of the things that are in here.

* About
The way it is constructed, the file is supposed to be a standalone configuration separate from =.emacs=, and simply loaded in.

That way, any private configuration or system-specific configuration can take place without making any changes to the core configuration in this repo.

So, if you cloned this repo directly into =.emacs.d= (Which is highly recommended), you can simply include it with:

#+BEGIN_SRC elisp :tangle ~/.emacs :padline no
  (org-babel-load-file "~/.emacs.d/Archemacs/Archemacs.org")
#+END_SRC

(You can use =C-c C-v t= while visiting this file in =org-mode= to export that code into =~/.emacs= if that's all you really need, though be warned that *this will overwrite your existing =.emacs=*)

* Installation in a nutshell
1. Backup your =~/.emacs=!! *(These steps will overwrite it!)*
2. Run =git -C ~/.emacs.d clone https://github.com/Archenoth/Archemacs.git=
3. Open this file in =org-mode=. (=emacs ~/.emacs.d/Archemacs/README.org=)
4. Tangle with =C-c C-v t=
5. Restart Emacs.

You might also want to grab =ripgrep= if you don't already have it, because this config uses that for projectile, dumb-jump, and grep (Though nothing should break without it)

If you want the font customization, please follow the instructions in [[./fonts.org][fonts.org]].
